[chains.bsc-chapel]
type = "evm"
stateMachineId = "EVM-97"
wrappedNativeDecimals = 18
rpcUrl = { env = "BSC_CHAPEL", url = "https://bnb-testnet.api.onfinality.io/public" }
consensusStateId = "BSC0"

[chains.bsc-chapel.assets]
WETH = "0xb8c77482e45f1f44de1745f52c74426c631bdd52"
DAI = "0x0000000000000000000000000000000000000000"

[chains.bsc-chapel.addresses]
IntentGateway = "0xb6C27F4beF379d0b5e2fe3Bb36c248D6B71f91A6"
Host = "0x8Aa0Dea6D675d785A882967Bf38183f6117C09b7"

[chains.gnosis-chiado]
type = "evm"
stateMachineId = "EVM-10200"
wrappedNativeDecimals = 18
rpcUrl = { env = "GNOSIS_CHIADO", url = "https://gnosis-chiado-rpc.publicnode.com" }
consensusStateId = "GNO0"

[chains.gnosis-chiado.assets]
WETH = "0x0000000000000000000000000000000000000000"
DAI = "0x0000000000000000000000000000000000000000"

[chains.gnosis-chiado.addresses]
IntentGateway = "0xb6C27F4beF379d0b5e2fe3Bb36c248D6B71f91A6"
Host = "0x58a41b89f4871725e5d898d98ef4bf917601c5eb"

[chains.hyperbridge-gargantua]
type = "substrate"
stateMachineId = "KUSAMA-4009"
rpcUrl = { env = "HYPERBRIDGE_GARGANTUA", url = "" }
consensusStateId = "PAS0" 