export declare const DEFAULT_DEPLOYMENT_TYPE = "primary";
export declare const ROOT_API_URL_PROD = "https://api.subquery.network";
export declare const BASE_PROJECT_URL = "https://managedservice.subquery.network";
export declare const BASE_TEMPLATE_URl = "https://templates.subquery.network";
export declare const ENDPOINT_REG: RegExp;
export declare const ADDRESS_REG: RegExp;
export declare const TOPICS_REG: RegExp;
export declare const FUNCTION_REG: RegExp;
export declare const CHAIN_ID_REG: RegExp;
export declare const CAPTURE_CHAIN_ID_REG: RegExp;
export declare const ACCESS_TOKEN_PATH: string;
export declare const DEFAULT_SUBGRAPH_MANIFEST = "subgraph.yaml";
export declare const DEFAULT_SUBGRAPH_SCHEMA = "schema.graphql";
export declare const DEFAULT_SUBQL_MANIFEST = "project.ts";
export declare const DEFAULT_SUBQL_SCHEMA = "schema.graphql";
