services:

  subquery-node-hyperbridge-gargantua:
    image: subquerynetwork/subql-node-substrate:latest
    restart: unless-stopped
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_DATABASE: ${DB_DATABASE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

    volumes:
      - ../configs:/app
      - ../dist:/app/dist
    command:
      - ${SUB_COMMAND:-}
      - -f=/app/hyperbridge-gargantua.yaml
      - --db-schema=app
      - --workers=${SUBQL_WORKERS:-5}
      - --batch-size=${SUBQL_BATCH_SIZE:-10}
      - --multi-chain
      - --unsafe
      - --log-level=info
      - --historical=false
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://subquery-node-hyperbridge-gargantua:3000/ready']
      interval: 3s
      timeout: 5s
      retries: 10

  subquery-node-bsc-chapel:
    image: subquerynetwork/subql-node-ethereum:v5.4.0
    restart: unless-stopped
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_DATABASE: ${DB_DATABASE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

    volumes:
      - ../configs:/app
      - ../dist:/app/dist
    command:
      - ${SUB_COMMAND:-}
      - -f=/app/bsc-chapel.yaml
      - --db-schema=app
      - --workers=${SUBQL_WORKERS:-5}
      - --batch-size=${SUBQL_BATCH_SIZE:-10}
      - --multi-chain
      - --unsafe
      - --log-level=info
      - --historical=false
      - --block-confirmations=5 
      - --store-cache-async=false 
      - --store-cache-threshold=100
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://subquery-node-bsc-chapel:3000/ready']
      interval: 3s
      timeout: 5s
      retries: 10

  subquery-node-gnosis-chiado:
    image: subquerynetwork/subql-node-ethereum:v5.4.0
    restart: unless-stopped
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_DATABASE: ${DB_DATABASE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

    volumes:
      - ../configs:/app
      - ../dist:/app/dist
    command:
      - ${SUB_COMMAND:-}
      - -f=/app/gnosis-chiado.yaml
      - --db-schema=app
      - --workers=${SUBQL_WORKERS:-5}
      - --batch-size=${SUBQL_BATCH_SIZE:-10}
      - --multi-chain
      - --unsafe
      - --log-level=info
      - --historical=false
      - --block-confirmations=5 
      - --store-cache-async=false 
      - --store-cache-threshold=100
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://subquery-node-gnosis-chiado:3000/ready']
      interval: 3s
      timeout: 5s
      retries: 10

  subquery-node-sepolia:
    image: subquerynetwork/subql-node-ethereum:v5.4.0
    restart: unless-stopped
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_DATABASE: ${DB_DATABASE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

    volumes:
      - ../configs:/app
      - ../dist:/app/dist
    command:
      - ${SUB_COMMAND:-}
      - -f=/app/sepolia.yaml
      - --db-schema=app
      - --workers=${SUBQL_WORKERS:-5}
      - --batch-size=${SUBQL_BATCH_SIZE:-10}
      - --multi-chain
      - --unsafe
      - --log-level=info
      - --historical=false
      - --block-confirmations=5 
      - --store-cache-async=false 
      - --store-cache-threshold=100
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://subquery-node-sepolia:3000/ready']
      interval: 3s
      timeout: 5s
      retries: 10

  graphql-engine:
    image: subquerynetwork/subql-query:v2.9.0
    ports:
      - 3000:3000

    restart: always
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_DATABASE: ${DB_DATABASE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    command:
      - --name=app
      - --playground

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5


