specVersion: 1.0.0
query:
  name: '@subql/query'
  version: '*'
projects:
  - ./hyperbridge-nexus.yaml
  - ./cere-mainnet.yaml
  - ./bifrost-mainnet.yaml
  - ./bsc-mainnet.yaml
  - ./base-mainnet.yaml
  - ./ethereum-mainnet.yaml
  - ./arbitrum-mainnet.yaml
  - ./optimism-mainnet.yaml
  - ./gnosis-mainnet.yaml
  - ./soneium-mainnet.yaml
