version: "3.8"

services:
    filler:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: hyperbridge-filler
        restart: unless-stopped
        volumes:
            - ${CONFIG_PATH:-../config.toml}:/app/config/config.toml:ro
        networks:
            - filler-network
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        healthcheck:
            test: ["CMD", "sh", "-c", "ps -ef | grep -v grep | grep run.sh"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 5s

volumes:
    filler-data:
        driver: local

networks:
    filler-network:
        driver: bridge
